- CHANGES.rst
- plone/app/widgets/browser/vocabulary.py
@alecpm i removed the check for IPloneSiteRoot, because getVocabulary should also be able to be called on other contexts, e.g. on INavigationRoot contexts from subsites in a collective.lineage based site.
https://github.com/plone/plone.app.widgets/compare/1.x...thet-getVocabulary-non-IPloneSiteRoot?expand=1#diff-cc8621ac4fb1caf4495921abbc02f895L194
Does this introduce a security problem, because e.g. a vocabulary could be customized on contexts other than IPloneSiteRoot? If this is the reason behind the IPloneSiteRoot check, it doesn't avoid customizing in IPloneSiteRoot directly. I marked the
> Change getVocabulary to work also on non IPloneSiteRoot contexts

- CHANGES.rst
- plone/app/widgets/utils.py
existing forecolor and backcolor button options will work if enabled (opt-in) in Plone 4 control panel, but only if this plugin is enabled.  This does not change user experience in OOTB TinyMCE control panel configuration, so low risk.  Includes change log entry and comment fix.
Second commit adds mapping of table styles in TinyMCE plone 4 control panel to table_class_list in TinyMCE JSON configuration.
> 1.x branch: enable more TinyMCE control panel feature mappings: textcolor plugin, table style/classname

- CHANGES.rst
- plone/app/widgets/utils.py
Fix incorrect options merge for TinyMCE widget.
Allow context url lookup to work with a wider variety of form types.
> Add navigation root support to related items widget.

- CHANGES.rst
- plone/app/widgets/utils.py
Trees are sorted on is_folderish at the moment, but they also are filtered to only show is_folderish contents. This allow easier finding of the folder/content we want.
> fix: Sort relateditems tree by sortable_title

- CHANGES.rst
- plone/app/widgets/utils.py
If the portal url is different from the navigation root one, the related item widget will not show contents outside of the navigation root.
I set vocabularyUrl as the portal url and basePath as the navigation root one to keep the current behavior but allow to find contents outside of it.
> fix: related items to search for the whole site rather than from the navigation root only

- CHANGES.rst
- plone/app/widgets/at.py
Use the RAW text for Archetypes based TinyMCE content, this fixes image handling with TinyMCE.
Signed-off-by: Rene Jochum <rene@jochums.at>
> Use RAW for Archetypes TinyMCE, fixes #145.

- CHANGES.rst
- plone/app/widgets/at.py
please see #111 ...
this should obsolete #112 which is quite dirty ... @jensens ?
also someone should check https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/Widget.py#L1213 for similar problem
> fix ajaxselectwidget value on form validation errors

- CHANGES.rst
- plone/app/widgets/tests/robot/test_querystring_widget.robot
I hope that this makes a sometimes failing test always pass.
Note: we should run the Jenkins tests at least twice before merging.
> Take more time during robot tests.

- CHANGES.rst
- plone/app/widgets/utils.py
- setup.py
Root the related items widget path bar to the top most visible site in the url and not the portal object itself.
This avoids related item widgets in subsites being able to break out of their virtual hosting root.
> better root for related items widget

- CHANGES.rst
- plone/app/widgets/tests/test_utils.py
- plone/app/widgets/utils.py
- Let the browsing/searching start path be the current context if its folderish or a level up.
- Include the ``contextPath`` option to exclude the current context from selection.
- Include the ``favorites`` option with the current context and the navigation root to quickly jump to these paths.
- Clean up obsolete options.
Fixes https://github.com/plone/Products.CMFPlone/issues/1974
> Related items widget options changes

- CHANGES.rst
- plone/app/widgets/tests/test_utils.py
- plone/app/widgets/utils.py
Fix broken get_tinymce_options when called with non-contentish contexts like form or field contexts.
Fixes: https://github.com/collective/collective.easyform/issues/67
> fix tinymce options with non-contentish contexts

- CHANGES.rst
- plone/app/widgets/configure.zcml
- plone/app/widgets/profiles/default/jsregistry.xml
- plone/app/widgets/profiles/default/metadata.xml
- plone/app/widgets/profiles/uninstall/jsregistry.xml
- plone/app/widgets/static/requirejs-reset.js
- plone/app/widgets/static/requirejs-unset.js
- plone/app/widgets/upgrades.py
Unset and reset ``define`` and ``require`` before and after the plone.app.widgets JavaScript bundle.
This avoids the infamous ``Mismatched anonymous define`` error with unbundled JavaScript supporting RequireJS.
See: http://requirejs.org/docs/errors.html#mismatch
> Unset and reset ``define`` and ``require``

- CHANGES.rst
- plone/app/widgets/static/requirejs-reset.js
- plone/app/widgets/static/requirejs-unset.js
Introduced in 5c75aa8d2a1637b80b461200afd5b2b51fd74f88 it might happen,
that there is no `define` or `require` defined. handle this gracefully.
> Failsafe requirejs unset/reset

- CHANGES.rst
- plone/app/widgets/tests/test_utils.py
- plone/app/widgets/utils.py
Pass parameter of subwidgets to the query string widget to get them properly initialized.
Fixes a problem where the related items widget behaved differently from other areas and the date widget didn't respect the users localization.
> QueryString widget: parameters for subwidgets

- CHANGES.rst
- plone/app/widgets/tests/test_utils.py
- plone/app/widgets/utils.py
Needs mockup 2.6.3 for that to work.
@jensens this one obsoletes https://github.com/plone/plone.app.relationfield/pull/21
I like it better to have the "recently used" pattern options managed here. This way, it uses the current field name for any instance of the related items widget. The downside is, the "recently used" feature is enabled per default for all instances of the related item widget (except those in the query string pattern).
I'd got for this one.
> Related items widget: show a recently used dropdown.

- CHANGES.rst
- plone/app/widgets/tests/robot/test_querystring_widget.robot
- plone/app/widgets/tests/test_robot.py
The test is flaky: http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/522/robot/Robot/Test%20Querystring%20Widget/Querystring%20Widget%20rows%20appear%20and%20disappear%20correctly/
And the test is unreadable for me: it clicks on several things and I have no idea what it is expecting to find there.
> Marked flaky robot test as non critical.

- CHANGES.rst
- plone/app/widgets/tests/robot/test_querystring_widget.robot
- plone/app/widgets/tests/test_robot.py
And maybe fix it by using keyword `Wait Until Page Does Not Contain Element`.
> Marked unstable robotframework test as noncritical.

- news/194.breaking
- plone/app/widgets/configure.zcml
- plone/app/widgets/factories.py
- plone/app/widgets/interfaces.py
- plone/app/widgets/tests/test_utils.py
- plone/app/widgets/utils.py
- setup.py
Deprecate it.
Refactor get_relateditems_options to be more specific.
More cleanup would be needed.
> get_ajaxselect_options is no longer used in plone.app.z3cform

- news/195.bugfix
- plone/app/widgets/tests/robot/test_datetime_widget.robot
- plone/app/widgets/tests/robot/test_querystring_widget.robot
- plone/app/widgets/tests/robot/test_select_widget.robot
I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.
Also re-enabled two previously disabled Robot tests.
In tandem with plone/plone.app.robotframework#110
Closes https://github.com/plone/plone.app.widgets/issues/195
This one actually stabilised a test for me locally when using a headless browser:
`As a contributor I can enter the date and time (test_datetime_widget.robot)`
> Default to a 4K x 4K browser window in Robot tests

- news/207.bugfix
- plone/app/widgets/tests/robot/common.robot
- plone/app/widgets/tests/robot/test_datetime_widget.robot
- plone/app/widgets/tests/robot/test_querystring_widget.robot
- plone/app/widgets/tests/robot/test_select_widget.robot
jQuery.size is deprecated since jQuery 1.8 and not available in jQuery 3.
> Robot tests: Replace deprecated jQuery.size with generic JavaScript.
